server {
    listen 80;
    server_name combatcare.pp.ua;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name combatcare.pp.ua;

    ssl_certificate /etc/letsencrypt/live/combatcare.pp.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/combatcare.pp.ua/privkey.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}
