# Generated by Django 6.0.2 on 2026-02-16 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_delete_chatuser_message_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чати'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
